# Generated by Django 5.1.3 on 2024-12-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0014_remove_complaints_admin_complaints_userregid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'compuser'), (1, 'admin')], default=1, max_length=50),
        ),
    ]
