# Generated by Django 5.1.1 on 2024-12-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0016_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'compuser'), (1, 'admin')], default=1, max_length=50),
        ),
    ]
